// AUTO-GENERATED SCRIPT: scripts/gen-logos.mjs
import { promises as fs } from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, '..');
const logosDir = path.join(projectRoot, 'src', 'logos');
const allBanksPath = path.join(projectRoot, 'src', 'all_banks.json');
const outFile = path.join(projectRoot, 'src', 'data', 'generated-logos.ts');

const EXT_PRIORITY = ['.svg', '.png', '.webp', '.jpg', '.jpeg'];

function getFormatFromExt(ext) {
  const clean = ext.toLowerCase().replace('.', '');
  if (clean === 'jpg') stroke: return 'jpeg';
  return clean;
}

async function main() {
  const entries = await fs.readdir(logosDir, { withFileTypes: true });
  const files = entries
    .filter((e) => e.isFile() && /\.(svg|png|jpg|jpeg|webp)$/i.test(e.name))
    .map((e) => e.name);

  // Group files by slug name
  const slugToFiles = new Map();
  for (const file of files) {
    const ext = path.extname(file).toLowerCase();
    const slug = path.basename(file, path.extname(file));
    if (slug === 'default-image') continue;

    if (!slugToFiles.has(slug)) {
      slugToFiles.set(slug, []);
    }
    slugToFiles.get(slug).push({ file, ext });
  }

  // Pick highest priority format for each slug (.svg > .png > .webp > .jpg)
  const resolvedLogos = [];
  const sortedSlugs = Array.from(slugToFiles.keys()).sort((a, b) => a.localeCompare(b));

  for (const slug of sortedSlugs) {
    const fileList = slugToFiles.get(slug);
    fileList.sort((a, b) => {
      const idxA = EXT_PRIORITY.indexOf(a.ext);
      const idxB = EXT_PRIORITY.indexOf(b.ext);
      return (idxA === -1 ? 99 : idxA) - (idxB === -1 ? 99 : idxB);
    });
    const best = fileList[0];
    resolvedLogos.push({
      slug,
      file: best.file,
      format: getFormatFromExt(best.ext)
    });
  }

  // Read all_banks.json to extract slugs & codes for TypeScript literal types
  let bankSlugs = [];
  let bankCodes = [];
  try {
    const rawBanks = await fs.readFile(allBanksPath, 'utf8');
    const banks = JSON.parse(rawBanks);
    bankSlugs = banks.map((b) => String(b.slug)).filter(Boolean);
    bankCodes = banks.map((b) => String(b.code)).filter(Boolean);
  } catch (err) {
    console.warn('Warning: Could not read all_banks.json for literal type generation', err);
  }

  const logoFileEntries = resolvedLogos.map((item) => `  "${item.slug}": "${item.file}",`).join('\n');
  const logoFormatEntries = resolvedLogos.map((item) => `  "${item.slug}": "${item.format}",`).join('\n');

  const slugTypeUnion = bankSlugs.length > 0
    ? bankSlugs.map((s) => JSON.stringify(s)).join(' | ')
    : 'string';

  const codeTypeUnion = bankCodes.length > 0
    ? Array.from(new Set(bankCodes)).map((c) => JSON.stringify(c)).join(' | ')
    : 'string';

  const content = `// AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
// Generated by scripts/gen-logos.mjs
import type { LogoFormat } from "../types";

/** Map of bank slugs to logo filenames in src/logos/ */
export const LOGO_FILES: Record<string, string> = {
${logoFileEntries}
};

/** Map of bank slugs to logo formats ('svg' | 'png' | 'webp' | 'jpeg') */
export const LOGO_FORMATS: Record<string, LogoFormat> = {
${logoFormatEntries}
};

/** List of all supported bank slugs */
export const SUPPORTED_SLUGS: readonly string[] = ${JSON.stringify(bankSlugs, null, 2)};

/** List of all supported bank codes */
export const SUPPORTED_CODES: readonly string[] = ${JSON.stringify(Array.from(new Set(bankCodes)), null, 2)};

/** Union of all official bank slugs */
export type GeneratedBankSlug = ${slugTypeUnion};

/** Union of all official NUBAN bank codes */
export type GeneratedBankCode = ${codeTypeUnion};
`;

  await fs.mkdir(path.dirname(outFile), { recursive: true });
  await fs.writeFile(outFile, content, 'utf8');
  console.log(`Successfully generated ${path.relative(projectRoot, outFile)} with ${resolvedLogos.length} logo mappings.`);
}

main().catch((err) => {
  console.error('Failed to generate logo metadata:', err);
  process.exit(1);
});
